### Neural Collaborative Filtering (NCF)

In [5]:
import pandas as pd 
import requests
from io import BytesIO
import streamlit as st

In [12]:
@st.cache_data
def load_and_clean_data():
    url = "https://github.com/Abdourahmane2/donne_etudiant/raw/main/base_finale.csv"
    response = requests.get(url)
    if response.status_code != 200:
        st.error("❌ Échec du téléchargement.")
        st.stop()

    data = pd.read_csv(BytesIO(response.content), low_memory=False)
    return data

2025-07-04 12:41:38.903 No runtime found, using MemoryCacheStorageManager

In [13]:
data = load_and_clean_data()

2025-07-04 12:41:46.274 No runtime found, using MemoryCacheStorageManager
2025-07-04 12:41:46.275 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-07-04 12:41:46.277 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-07-04 12:41:46.278 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-07-04 12:41:46.797 Thread 'Thread-17': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-07-04 12:41:46.800 Thread 'Thread-17': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-07-04 12:42:04.685 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-07-04 12:42:04.688 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
data['DEPARTEMENT FORMATION'].unique()

array(['Economie', 'Gestion', 'Institut des Sciences de la Terre',
       'Physique', 'Production Audiovisuelle',
       'Administration Gestion et Contrôle des Activités physiques socio-éducative',
       'Mathématiques-Informatique', 'Journalisme', '.....',
       'Droit Privé', 'I.F.R.P.D.S.R.', 'Droit Public', 'Anglais',
       'Education physique et des Sports', 'Chimie', 'Physique-Chimie',
       'Sciences de la Vie et de la Terre', 'Géologie',
       'Biologie Animale', 'Institut des Métiers du Droit',
       'Sciences Politiques', "Institut des Sciences de l'Environnement",
       'Documentation', 'Histoire-Géographie',
       "Institut de Formation en Administration et Création d'Entreprise",
       'Langues Romanes', '....', 'Ecole Doctorale',
       'Sciences Biologiques et Pharmaceutiques appliquées',
       'Communication',
       'Biologie Médicale et Explorations Fonctionnelles', 'Archives',
       'Sciences Pharmaceutiques, physiques et chimiques',
       'Administration et gestion de l?éducation et de la formation',
       'Techniques économique et gestion', 'Histoire', 'Géographie',
       'Lettres Modernes', 'Arabe', 'Allemand', 'Langues Anciennes',
       'Langues et civilisations slaves', 'Linguistique', 'Philosophie',
       'Sociologie', 'Lettres modernes et classiques', 'Perse',
       'Biologie Végétale', 'Didactique de l?Anglais',
       'Economie Familiale', 'I.F.E.', 'Génie Chimique',
       'Aménagement du Territoire Environnement et Gestion Urbaine',
       'Mathématiques', 'Développement Communautaire et Formation',
       'Médecine interne et Spécialités médicales', 'Génie Informatique',
       'Centre de Recherche et de Formation pour le Développement Economique et Social',
       'Planification Economique et Gestion des Organisations',
       'Animation Socio-Educative',
       'Institut de la gouvernance territoriale',
       "Institut Supérieur d'Agriculture et Entreprenariat",
       'Génie Civil', 'Génie Mécanique',
       'Chirurgie et Spécialités Chirurgicales', 'Génie Electrique',
       'Histoire du Droit', "Sciences de l'Education", 'Russe',
       'Techniques administratives et de Secrétariat',
       "INSTITUT DES DROITS DE L'HOMME ET DE LA PAIX",
       "Centre de Recherche et de formation aux technologies de l'internet",
       'Psychologie', 'Institut des Langues étrangères appliquées',
       'C.E.R.E.R.', 'Techniques industrielles',
       'Psychologues conseillers', 'Section E'], dtype=object)

:

In [ ]:
data.columns = data.columns.str.lower().str.replace(' ', '_')
data.columns

Index(['numero', 'ine', 'nom', 'prenom', 'date_de_naissance', 'sexe',
       'mention_bacc', 'annee_bacc', 'nationalite', 'serie_bacc',
       'etablissment_code', 'niveau_section', 'annee_inscription',
       'annee_universitaire', 'type_formation', 'code_niveau',
       'niveau_lmd_et_non_lmd', 'systeme', 'departement_formation', 'resultat',
       'mention', 'moyenne_annuelle', 'credit', 'session'],
      dtype='object')

In [ ]:
data.head()

,numero,ine,nom,prenom,date_de_naissance,sexe,mention_bacc,annee_bacc,nationalite,serie_bacc,...,type_formation,code_niveau,niveau_lmd_et_non_lmd,systeme,departement_formation,resultat,mention,moyenne_annuelle,credit,session
0,2005023MB,NaN,BA,Aminata Mame Arete,14/06/1982,F,PA,2005.0,Sénégalaise,S2,...,I,4,4A,Classique,Economie,A obtenu le diplôme,NaN,"10,35",60.0,SESSION NORMALE
1,200602EXK,NaN,FALL,El Hadji Malick,30/07/1985,M,PA,2006.0,Sénégalaise,S2,...,I,4,4A,Classique,Economie,A obtenu le diplôme,NaN,"10,26",60.0,SESSION NORMALE
2,200602FFL,NaN,TINE,Hortence Ndélla,17/07/1987,F,PA,2006.0,Sénégalaise,S2,...,I,4,4A,Classique,Gestion,A obtenu le diplôme,NaN,"10,73",NaN,SESSION NORMALE
3,200602IEV,NaN,TRAORE,Amy,14/09/1986,F,PA,2006.0,Sénégalaise,G,...,I,4,4A,Classique,Gestion,A obtenu le diplôme,NaN,"12,02",60.0,SESSION NORMALE
4,200602QRW,NaN,NDIAYE,Moussa,13/05/1984,M,PA,2006.0,Sénégalaise,S2,...,I,4,4A,Classique,Economie,A obtenu le diplôme,NaN,"10,44",60.0,SESSION NORMALE

In [ ]:
data.isnull().sum()* 100 / len(data)

numero                    0.000000
ine                       4.298670
nom                       0.000000
prenom                    0.000000
date_de_naissance         0.000000
sexe                      0.000000
mention_bacc              0.001605
annee_bacc                0.001605
nationalite               0.000000
serie_bacc                1.152653
etablissment_code         0.000000
niveau_section            0.000000
annee_inscription         0.000000
annee_universitaire       0.000000
type_formation            0.000000
code_niveau               0.000000
niveau_lmd_et_non_lmd     0.000000
systeme                   0.000000
departement_formation     0.000000
resultat                  0.024479
mention                  61.372562
moyenne_annuelle          5.393269
credit                    3.948875
session                   0.024211
dtype: float64

### Gerer les valeurs manquantes

In [ ]:
data = data.drop(columns=['ine'])

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 747580 entries, 0 to 747579
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   numero                 747580 non-null  object
 1   nom                    747580 non-null  object
 2   prenom                 747580 non-null  object
 3   date_de_naissance      747580 non-null  object
 4   sexe                   747580 non-null  object
 5   mention_bacc           747568 non-null  object
 6   annee_bacc             747568 non-null  float64
 7   nationalite            747580 non-null  object
 8   serie_bacc             738963 non-null  object
 9   etablissment_code      747580 non-null  object
 10  niveau_section         747580 non-null  object
 11  annee_inscription      747580 non-null  int64
 12  annee_universitaire    747580 non-null  object
 13  type_formation         747580 non-null  object
 14  code_niveau            747580 non-null  int64
 15  niveau_lmd_et_non_lmd  747580 non-null  object
 16  systeme                747580 non-null  object
 17  departement_formation  747580 non-null  object
 18  resultat               747397 non-null  object
 19  mention                288771 non-null  object
 20  moyenne_annuelle       707261 non-null  object
 21  credit                 718059 non-null  object
 22  session                747399 non-null  object
dtypes: float64(1), int64(2), object(20)
memory usage: 131.2+ MB

In [ ]:
#afficher le type de chaque colonne
data['moyenne_annuelle'] = pd.to_numeric(data['moyenne_annuelle'], errors='coerce')
data['moyenne_annuelle'].dtype
#remplacer les valeurs manquantes par la moyenne des etudiants similares 
data['moyenne_annuelle'] = data.groupby(['resultat', 'mention_bacc'])['moyenne_annuelle'].transform(lambda x: x.fillna(x.mean()))

In [ ]:
#supprimer la colonne mention car % de valeurs trop importante remplacer par la mode peut creer un desiquilibre  
data = data.drop(columns=['mention'])

In [ ]:
#regrouper les series bacc en 3 categories 
import pandas as pd
def serie_bac_type(serie):
    s = str(serie).upper().strip()
    if any(x in s for x in ['S', 'SCI', 'D', 'E', 'F6', 'F4', 'F5', 'S2', 'S3', 'S4', 'S5', 'SM', 'A2', 'A3', 'S1A', 'S2A']):
        return 'Scientifique'
    elif any(x in s for x in ['L', 'A', 'AR', 'L1', 'L2', 'L\'', 'L1B', 'L1A', 'LA', 'SNA', 'SB']):
        return 'Littéraire'
    elif any(x in s for x in ['G', 'T', 'STG', 'S1', 'S2', 'S3', 'S4', 'S5', 'T1', 'F7', 'CAEP', 'STIDD', 'STEG']):
        return 'Tertiaire'
    else:
        return 'Autre'

data['categorie_bac'] = data['serie_bacc'].apply(serie_bac_type)

In [ ]:
data['mention_bacc'].unique()

array(['PA', 'AB', nan, 'ka', 'BI', 'TB', '50', 'da', 'gu', 'TH', 'mb',
       'lo', '..', 'Ab', 'BA', 'LV', 'ru', 'A', 'HO'], dtype=object)

In [ ]:
#gerer les mentions bacc
def clean_mention(mention):
    mention = str(mention).upper().strip()
    # Standardiser les mentions valides
    if mention == 'AB' or mention == 'Ab':
        return 'Assez Bien'
    elif mention == 'TB' or mention == 'TH':
        return 'Très Bien'
    elif mention == 'BI':
        return 'Bien'
    elif mention == 'A':
        return 'Assez Bien'
    elif mention == 'PA':
        return 'Passable'
    elif mention in ['KA', 'GU', 'MB', 'LO', '..', 'BA', 'LV', 'RU', 'HO' , '50']:
        return 'non renseigne'  


# Appliquer la fonction de nettoyage à la colonne 'mention_bacc'
data['mention_bacc'] = data['mention_bacc'].apply(clean_mention)

#remplaceer les mentions non renseignées par la mention la plus fréquente
most_frequent_mention = data['mention_bacc'].mode()[0]
data['mention_bacc'] = data['mention_bacc'].replace('non renseigne', most_frequent_mention)
data['mention_bacc'].fillna(most_frequent_mention , inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_23852\3178570937.py:25: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['mention_bacc'].fillna(most_frequent_mention , inplace=True)

In [ ]:
data['mention_bacc'].isnull().sum()

0

In [ ]:
#annee de bac 
data['annee_bacc'].fillna(data['annee_bacc'].mode()[0] , inplace=True) #remplacer par la valeur la plus fréquente

C:\Users\HP\AppData\Local\Temp\ipykernel_23852\2577514542.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['annee_bacc'].fillna(data['annee_bacc'].mode()[0] , inplace=True) #remplacer par la valeur la plus fréquente

In [ ]:
#supprimer les lignes avec des valeurs manquantes dans 'annee_bacc'
data = data.dropna(subset=['moyenne_annuelle', 'credit', 'session' , 'resultat'])

In [ ]:
data.isnull().sum()* 100 / len(data)

numero                   0.000000
nom                      0.000000
prenom                   0.000000
date_de_naissance        0.000000
sexe                     0.000000
mention_bacc             0.000000
annee_bacc               0.000000
nationalite              0.000000
serie_bacc               0.907799
etablissment_code        0.000000
niveau_section           0.000000
annee_inscription        0.000000
annee_universitaire      0.000000
type_formation           0.000000
code_niveau              0.000000
niveau_lmd_et_non_lmd    0.000000
systeme                  0.000000
departement_formation    0.000000
resultat                 0.000000
moyenne_annuelle         0.000000
credit                   0.000000
session                  0.000000
categorie_bac            0.000000
dtype: float64

In [ ]:
duplication = data.duplicated() 
print(f"Nombre de lignes dupliquées : {duplication.sum()}")

Nombre de lignes dupliquées : 28

In [ ]:
data.drop_duplicates(inplace=True)

#### GradientBoostingRegressor

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor , RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder 
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from sklearn.tree import DecisionTreeRegressor

In [ ]:
print(data.head(10))

       numero     nom              prenom date_de_naissance sexe mention_bacc  \
0   2005023MB      BA  Aminata Mame Arete        14/06/1982    F     Passable
1   200602EXK    FALL     El Hadji Malick        30/07/1985    M     Passable
3   200602IEV  TRAORE                 Amy        14/09/1986    F     Passable
4   200602QRW  NDIAYE              Moussa        13/05/1984    M     Passable
5   200702V4X    CISS              Moussa        08/10/1986    M     Passable
6   200702WP4   MBAYE              Ablaye        10/10/1985    M     Passable
7   200702Y1K    FAYE           Moustapha        18/02/1987    M     Passable
8   200702Y9P   POUYE               Adama        15/05/1987    F     Passable
9   200702Z7Z      SY  Papa Mamadou Mbodj        01/10/1986    M     Passable
10  200702ZQ0      BA          Baba Demba        03/02/1985    M     Passable

    annee_bacc  nationalite serie_bacc etablissment_code  ... type_formation  \
0       2005.0  Sénégalaise         S2             FASEG  ...              I
1       2006.0  Sénégalaise         S2             FASEG  ...              I
3       2006.0  Sénégalaise          G             FASEG  ...              I
4       2006.0  Sénégalaise         S2             FASEG  ...              I
5       2007.0  Sénégalaise         S2             FASEG  ...              I
6       2007.0  Sénégalaise         S2             FASEG  ...              I
7       2007.0  Sénégalaise         S2             FASEG  ...              I
8       2007.0  Sénégalaise         S2             FASEG  ...              I
9       2007.0  Sénégalaise         S2             FASEG  ...              I
10      2007.0  Sénégalaise         S2             FASEG  ...              I

    code_niveau niveau_lmd_et_non_lmd    systeme  departement_formation  \
0             4                    4A  Classique               Economie
1             4                    4A  Classique               Economie
3             4                    4A  Classique                Gestion
4             4                    4A  Classique               Economie
5             4                    4A  Classique               Economie
6             4                    4A  Classique                Gestion
7             4                    4A  Classique               Economie
8             4                    4A  Classique               Economie
9             4                    4A  Classique               Economie
10            4                    4A  Classique                Gestion

               resultat moyenne_annuelle credit           session  \
0   A obtenu le diplôme        11.147133   60.0   SESSION NORMALE
1   A obtenu le diplôme        11.147133   60.0   SESSION NORMALE
3   A obtenu le diplôme        11.147133   60.0   SESSION NORMALE
4   A obtenu le diplôme        11.147133   60.0   SESSION NORMALE
5   A obtenu le diplôme        11.147133   60.0   SESSION NORMALE
6   A obtenu le diplôme        11.147133   60.0  DEUXIEME SESSION
7   A obtenu le diplôme        11.147133   60.0   SESSION NORMALE
8   A obtenu le diplôme        11.147133   60.0   SESSION NORMALE
9   A obtenu le diplôme        11.147133   60.0   SESSION NORMALE
10  A obtenu le diplôme        11.147133   60.0   SESSION NORMALE

    categorie_bac
0    Scientifique
1    Scientifique
3       Tertiaire
4    Scientifique
5    Scientifique
6    Scientifique
7    Scientifique
8    Scientifique
9    Scientifique
10   Scientifique

[10 rows x 23 columns]

In [ ]:
data['code_niveau'].value_counts()

code_niveau
1     281788
2     195671
3     153333
4      54794
5      32267
6         92
7         17
10         3
9          3
8          2
11         1
12         1
Name: count, dtype: int64

In [ ]:
#prendre que code niveau 1 etudiant
data = data[data['code_niveau'] == 1]
print(data.head())

         numero    nom        prenom date_de_naissance sexe mention_bacc  \
1517  201104M7L  KASSE        Cheikh        04/08/1989    M     Passable
1518  201104NEY   FALL   Aïta Diagne        23/06/1990    F     Passable
1519  201205309  SAMBE        Tamsir        24/09/1993    M     Passable
1520  2012056VA   COLY  Mamadou Sana        17/09/1990    M     Passable
1521  2012059T1   PENE      Mouhamed        15/06/1992    M     Passable

      annee_bacc  nationalite serie_bacc etablissment_code  ...  \
1517      2011.0  Sénégalaise          G             FASEG  ...
1518      2011.0  Sénégalaise          G             FASEG  ...
1519      2012.0  Sénégalaise         L2              FSJP  ...
1520      2012.0  Sénégalaise          G             FASEG  ...
1521      2012.0  Sénégalaise          G             FASEG  ...

     type_formation  code_niveau niveau_lmd_et_non_lmd systeme  \
1517              I            1                    L1     LMD
1518              I            1                    L1     LMD
1519              I            1                    L1     LMD
1520              I            1                    L1     LMD
1521              I            1                    L1     LMD

      departement_formation           resultat moyenne_annuelle credit  \
1517                Gestion           Redouble              0.0    0.0
1518                Gestion           Redouble              2.0   12.0
1519            Droit Privé           Redouble              8.0   23.0
1520                Gestion  Autorisé à passer             10.0   48.0
1521                Gestion              Passe             12.0   60.0

               session  categorie_bac
1517  DEUXIEME SESSION      Tertiaire
1518  DEUXIEME SESSION      Tertiaire
1519  Deuxième Session     Littéraire
1520  DEUXIEME SESSION      Tertiaire
1521  DEUXIEME SESSION      Tertiaire

[5 rows x 23 columns]

In [ ]:
data['resultat'].unique()

array(['Redouble', 'Autorisé à passer', 'Passe', 'Année non validée',
       'A obtenu le diplôme', 'Année validée', 'Exclu',
       'Autorisé à faire la session 2'], dtype=object)

In [ ]:
data.head()

,numero,nom,prenom,date_de_naissance,sexe,mention_bacc,annee_bacc,nationalite,serie_bacc,etablissment_code,...,type_formation,code_niveau,niveau_lmd_et_non_lmd,systeme,departement_formation,resultat,moyenne_annuelle,credit,session,categorie_bac
1517,201104M7L,KASSE,Cheikh,04/08/1989,M,Passable,2011.0,Sénégalaise,G,FASEG,...,I,1,L1,LMD,Gestion,Redouble,0.0,0.0,DEUXIEME SESSION,Tertiaire
1518,201104NEY,FALL,Aïta Diagne,23/06/1990,F,Passable,2011.0,Sénégalaise,G,FASEG,...,I,1,L1,LMD,Gestion,Redouble,2.0,12.0,DEUXIEME SESSION,Tertiaire
1519,201205309,SAMBE,Tamsir,24/09/1993,M,Passable,2012.0,Sénégalaise,L2,FSJP,...,I,1,L1,LMD,Droit Privé,Redouble,8.0,23.0,Deuxième Session,Littéraire
1520,2012056VA,COLY,Mamadou Sana,17/09/1990,M,Passable,2012.0,Sénégalaise,G,FASEG,...,I,1,L1,LMD,Gestion,Autorisé à passer,10.0,48.0,DEUXIEME SESSION,Tertiaire
1521,2012059T1,PENE,Mouhamed,15/06/1992,M,Passable,2012.0,Sénégalaise,G,FASEG,...,I,1,L1,LMD,Gestion,Passe,12.0,60.0,DEUXIEME SESSION,Tertiaire

In [ ]:
data['annee_bacc'].unique()

array([2011., 2012., 1999., 1996., 2005., 2009., 2010., 2008., 1991.,
       2007., 2003., 2001., 2006., 2000., 1997., 1995., 1998., 1989.,
       1984., 1983., 2002., 2004., 1994., 1992.,   93., 1988., 1986.,
       1993., 1990., 1987., 2013., 2014., 2015., 2016.,   96., 2017.,
         95., 1985., 2022., 1975., 2018., 2019., 1978., 2020.,  219.,
       2021., 1976., 2023.])

In [ ]:

#mapper les resultas avec 1 et 0
mapping_resultats = {
    'Redouble': 0,
    'Passe': 1,
    'Autorisé à passer': 1,
    'A obtenu le diplôme': 1,
    'Année validée': 1,
    'Exclu': 0,
    'Année non validée': 0,
    'Autorisé à faire la session 2': 1
}
data['resultat'] = data['resultat'].map(mapping_resultats)

In [ ]:
data['resultat'].value_counts()

resultat
0    162866
1    118922
Name: count, dtype: int64

In [ ]:
data['serie_bacc'].unique()
#L1 , L2 , L'1 , LA , S1 , S2 , S3 , S4 , S5 ,  T1 , T2 , G , F6 , S1A ,S2A

array(['G', 'L2', "L'1", 'S2', 'S1', 'D', 'A2', nan, 'A4', 'A', 'T1', 'C',
       'S', 'A3', 'S3', 'L1B', 'LA', 'S5', 'S2A', 'E', "L'", 'B', 'SNB',
       'L1A', 'G2', 'SNA', 'LAR', 'a3', 'S4', 'S1A', 'STEG', 'SM', 'L',
       'T', 'ES'], dtype=object)

In [ ]:
print(data['resultat'].value_counts(normalize=True) * 100)

resultat
0    57.797351
1    42.202649
Name: proportion, dtype: float64

In [ ]:
data.columns

Index(['numero', 'nom', 'prenom', 'date_de_naissance', 'sexe', 'mention_bacc',
       'annee_bacc', 'nationalite', 'serie_bacc', 'etablissment_code',
       'niveau_section', 'annee_inscription', 'annee_universitaire',
       'type_formation', 'code_niveau', 'niveau_lmd_et_non_lmd', 'systeme',
       'departement_formation', 'resultat', 'moyenne_annuelle', 'credit',
       'session', 'categorie_bac'],
      dtype='object')

In [ ]:

# Fonction pour filtrer les étudiants en fonction des critères
def filtrer_etudiants(df, age_min, age_max, annee_bac , serie_bacc, nationalite):
    # Convertir la colonne 'date_de_naissance' en format datetime
    df['date_de_naissance'] = pd.to_datetime(df['date_de_naissance'], errors='coerce')

    # Calculer l'âge à partir de la date de naissance
    df['age'] = df['annee_bacc'] - df['date_de_naissance'].dt.year
    
    # Filtrer les étudiants en fonction des critères fournis
    df_filtre = df[
        (df['age'] >= age_min) & (df['age'] <= age_max) & 
        (df['serie_bacc'] == serie_bacc) & 
        (df['nationalite'] == nationalite) &
        (df['annee_bacc'] == annee_bac -1)  #prendre que les etudiands inscrites l'annee d'avant
    ]
    return df_filtre

# Fonction pour générer les statistiques par mention de bac et département
def statistiques_par_mention_bac(df_filtre):
    if df_filtre.empty:
        return "Aucun étudiant correspondant à ces critères."

    # Dictionnaire pour stocker les résultats
    stats_list = []
    
    for mention in df_filtre['mention_bacc'].unique():
        # Filtrer par mention
        df_mention = df_filtre[df_filtre['mention_bacc'] == mention]
        
        # Calcul des statistiques par département
        for departement in df_mention['departement_formation'].unique():
            # Filtrer par département
            df_departement = df_mention[df_mention['departement_formation'] == departement]
            
            # Si aucun étudiant n'est orienté dans ce département, on le saute
            if df_departement.empty:
                continue
            
            # Calcul du taux de réussite (résultat == "Passe")
            taux_reussite = (df_departement['resultat'] == 1).mean() * 100
            
            # Calcul du taux de redoublement (résultat == "Redouble")
            taux_redoublement = (df_departement['resultat'] ==0).mean() * 100
            
            # Calcul de la moyenne obtenue dans ce département
            moyenne_departement = df_departement['moyenne_annuelle'].mean()
            
            # Nombre d'étudiants orientés dans ce département
            nombre_etudiants = len(df_departement)
            
            # Ajouter les résultats dans la liste
            stats_list.append({
                'Mention de Bac': mention,
                'Département': departement,
                'Taux de réussite': taux_reussite,
                'Taux de redoublement': taux_redoublement,
                'Moyenne obtenue': moyenne_departement,
                'Nombre d\'étudiants orientés': nombre_etudiants
            })

    # Convertir les résultats en DataFrame
    stats_df = pd.DataFrame(stats_list)
    
    return stats_df

# Exemple pour l'étudiant
age_min = 18
age_max = 20
serie_bacc = 'L2'  # Série scientifique
nationalite = 'Sénégalaise'
annee_bac = 2023  # Année de baccalauréat

# Filtrer les étudiants selon les critères
df_similaires = filtrer_etudiants(data, age_min, age_max, annee_bac , serie_bacc, nationalite)

# Calculer les statistiques des étudiants filtrés par mention de bac
stats_similaires_mention = statistiques_par_mention_bac(df_similaires)

# Affichage des résultats sous forme de DataFrame 
print("voici quelques statistiques  des etudiants similaires orientes l'année d'avant :") 
stats_similaires_mention

voici quelques statistiques  des etudiants similaires orientes l'année d'avant :

,Mention de Bac,Département,Taux de réussite,Taux de redoublement,Moyenne obtenue,Nombre d'étudiants orientés
0,Passable,Institut de Formation en Administration et Cré...,83.870968,16.129032,10.016184,62
1,Passable,Sociologie,72.413793,27.586207,8.743930,116
2,Passable,Droit Privé,30.632411,69.367589,7.017720,506
3,Passable,Géographie,62.527716,37.472284,8.068044,451
4,Passable,Sciences Politiques,50.314465,49.685535,8.157787,159
5,Passable,Histoire,43.573668,56.426332,6.744426,319
6,Passable,Psychologie,62.068966,37.931034,7.833409,29
7,Passable,Philosophie,33.613445,66.386555,6.202245,238
8,Passable,Education physique et des Sports,100.000000,0.000000,11.086147,6
9,Passable,Institut des Langues étrangères appliquées,100.000000,0.000000,11.335676,2
10,Passable,Institut des Métiers du Droit,100.000000,0.000000,11.335676,3
11,Passable,Aménagement du Territoire Environnement et Ges...,100.000000,0.000000,11.036241,5
12,Passable,Développement Communautaire et Formation,100.000000,0.000000,10.836618,3
13,Passable,Anglais,100.000000,0.000000,11.335676,1
14,Passable,Communication,100.000000,0.000000,11.335676,2
15,Passable,Institut de la gouvernance territoriale,100.000000,0.000000,11.335676,3
16,Passable,Administration Gestion et Contrôle des Activit...,100.000000,0.000000,10.836618,9
17,Passable,Lettres Modernes,0.000000,100.000000,5.101151,1
18,Passable,Animation Socio-Educative,100.000000,0.000000,11.335676,2
19,Passable,Langues Anciennes,100.000000,0.000000,11.335676,1
20,Assez Bien,Philosophie,46.153846,53.846154,6.313458,13
21,Assez Bien,Droit Privé,57.500000,42.500000,8.315849,120
22,Assez Bien,Géographie,70.873786,29.126214,8.932498,103
23,Assez Bien,Sciences Politiques,52.380952,47.619048,7.851236,21
24,Assez Bien,Histoire,50.000000,50.000000,6.461796,12
25,Assez Bien,Institut de Formation en Administration et Cré...,40.000000,60.000000,6.985029,5
26,Assez Bien,Sociologie,56.521739,43.478261,7.551016,23
27,Assez Bien,Institut de la gouvernance territoriale,100.000000,0.000000,11.822861,9
28,Assez Bien,Centre de Recherche et de formation aux techno...,66.666667,33.333333,8.810056,6
29,Assez Bien,Psychologie,83.333333,16.666667,10.153898,6
30,Assez Bien,Aménagement du Territoire Environnement et Ges...,100.000000,0.000000,11.822861,1
31,Assez Bien,Développement Communautaire et Formation,100.000000,0.000000,11.822861,1
32,Bien,Géographie,50.000000,50.000000,7.258401,2
33,Bien,Sociologie,100.000000,0.000000,12.424802,2
34,Bien,Droit Privé,55.000000,45.000000,7.775041,20
35,Bien,Centre de Recherche et de formation aux techno...,50.000000,50.000000,7.258401,2
36,Bien,Psychologie,0.000000,100.000000,0.000000,1
37,Bien,Histoire,100.000000,0.000000,13.000000,1
38,Bien,Education physique et des Sports,100.000000,0.000000,12.424802,1
39,Bien,Sciences Politiques,100.000000,0.000000,12.424802,1

In [4]:
data['departement_formation'].unique()

NameError: name 'data' is not defined